services:
  storage:
    image: redis
    volumes:
      - ../counter/data:/data
    networks:
      - my-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - my-network
    depends_on:
      - mongo

  counter:
    build: ../counter
    ports:
      - 3003:3003
    networks:
      - my-network
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    depends_on: 
      - storage

  library:
    build: .
    ports:
      - 80:3002
    networks:
      - my-network
    environment:
      - PORT=3002
      - COUNTER_URL=counter:3003
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=books
      - DB_HOST=mongodb://mongo
    depends_on:
      - mongo
      - counter

networks:
  my-network:
