services:
  storage:
    image: redis
    volumes:
      - ../counter/data:/data
    networks:
      - my-network
  counter:
    build: ../counter
    ports:
      - 3003:3003
    networks:
      - my-network
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    depends_on: 
      - storage
  library:
    build: .
    ports:
      - 80:3002
    networks:
      - my-network
    environment:
      - PORT=3002
    depends_on:
      - counter
networks:
  my-network:
